-- Execute este arquivo no SQL Editor do Supabase uma única vez.
create table if not exists public.access_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  namespace text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, namespace)
);

alter table public.access_requests enable row level security;
alter table public.finance_records enable row level security;

drop policy if exists "finance_select_own" on public.finance_records;
create policy "finance_select_own" on public.finance_records for select
  to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "finance_insert_own" on public.finance_records;
create policy "finance_insert_own" on public.finance_records for insert
  to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "finance_update_own" on public.finance_records;
create policy "finance_update_own" on public.finance_records for update
  to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "finance_delete_own" on public.finance_records;
create policy "finance_delete_own" on public.finance_records for delete
  to authenticated using ((select auth.uid()) = user_id);

revoke all on public.access_requests from anon, authenticated;
grant select, insert, update, delete on public.finance_records to authenticated;
grant usage, select on sequence public.finance_records_id_seq to authenticated;
