"use client";
import {useMemo,useState} from "react";
import {ArrowDownLeft,ArrowUpRight,Bell,CalendarDays,Check,ChevronDown,Circle,CircleCheck,CreditCard,KeyRound,Landmark,LayoutDashboard,LogOut,Menu,PanelLeftClose,PanelLeftOpen,Pencil,PiggyBank,Plus,ReceiptText,Search,Settings,Sparkles,Target,Trash2,TrendingUp,Upload,Wallet,WalletCards,X} from "lucide-react";
import {usePersistedFinance} from "../lib/use-persisted-finance";
type Tx={id:number,date:string,description:string,category:string,icon:string,account:string,value:number,status:"confirmado"|"previsto"|"revisar",installment?:string};
const initial:Tx[]=[
{id:1,date:"03 set",description:"Supermercado Condor",category:"Mercado",icon:"🛒",account:"Nubank • 4421",value:-387.42,status:"confirmado"},
{id:2,date:"05 set",description:"Salário — Escola",category:"Renda",icon:"💼",account:"Conta principal",value:5498.70,status:"previsto"},
{id:3,date:"08 set",description:"Mercado Livre",category:"Compras",icon:"🛍️",account:"Inter • 0917",value:-246.80,status:"confirmado",installment:"3/6"},
{id:4,date:"10 set",description:"Aluguel",category:"Moradia",icon:"🏠",account:"Conta principal",value:-1450,status:"previsto"},
{id:5,date:"12 set",description:"Spotify",category:"Assinaturas",icon:"🔁",account:"Nubank • 4421",value:-21.90,status:"previsto"},
{id:6,date:"15 set",description:"Posto Avenida",category:"Transporte",icon:"🚗",account:"Inter • 0917",value:-250,status:"revisar"}];
const fmt=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Math.abs(n));
export default function Home({userEmail,onLogout}:{userEmail:string;onLogout:()=>void}){
const [section,setSection]=useState("Visão geral"),[mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),[month,setMonth]=useState("Setembro 2026"),[txs,setTxs,saveState]=usePersistedFinance<Tx[]>("dashboard-transactions",initial),[importOpen,setImportOpen]=useState(false),[addOpen,setAddOpen]=useState(false),[paste,setPaste]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
const nav=[["Visão geral",LayoutDashboard],["Planejamento",CalendarDays],["Lançamentos",ArrowUpRight],["Cartões",CreditCard],["Contas",Landmark],["Metas e reservas",Target],["Relatório anual",PiggyBank],["Acessos",KeyRound]] as const;
const spent=txs.filter(x=>x.value<0).reduce((a,b)=>a-b.value,0),income=txs.filter(x=>x.value>0).reduce((a,b)=>a+b.value,0),filtered=txs.filter(t=>t.value<0&&(t.description+t.category+t.account).toLowerCase().includes(query.toLowerCase()));
const cats=useMemo(()=>Object.entries(txs.filter(t=>t.value<0).reduce((a,t)=>({...a,[t.category]:(a[t.category]||0)-t.value}),{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]),[txs]);
function doImport(){const lines=paste.split(/\n/).filter(Boolean),added:Tx[]=[];lines.forEach((line,j)=>{const m=line.match(/(\d{2}[\/\-]\d{2}(?:[\/\-]\d{2,4})?).*?([+-]?\s?R?\$?\s?[\d.]+,\d{2})/);if(!m)return;const raw=m[2].replace(/[^\d,\-]/g,"").replace(".","").replace(",",".");const desc=line.slice(m.index!+m[0].indexOf(m[1])+m[1].length,line.lastIndexOf(m[2])).replace(/[;|]/g," ").trim()||"Lançamento importado",low=desc.toLowerCase(),map=low.includes("merc")?["Mercado","🛒"]:low.includes("posto")||low.includes("uber")?["Transporte","🚗"]:low.includes("sal")?["Renda","💼"]:low.includes("ifood")?["Delivery","🛵"]:["A confirmar","✨"];added.push({id:Date.now()+j,date:m[1].slice(0,5).replace("/"," "),description:desc,category:map[0],icon:map[1],account:"Extrato importado",value:Number(raw),status:map[0]==="A confirmar"?"revisar":"confirmado"})});if(!added.length){setNotice("Não identifiquei linhas com data e valor. Cole uma movimentação por linha.");return}const unique=added.filter(n=>!txs.some(t=>t.description===n.description&&t.value===n.value&&t.date===n.date));setTxs(p=>[...unique,...p]);setNotice(`${unique.length} lançamentos novos; ${added.length-unique.length} duplicados ignorados.`);setPaste("")}
return <div className={collapsed?"app-shell sidebar-collapsed":"app-shell"}>
<aside className={mobile?"sidebar open":"sidebar"}><button className="collapse-sidebar" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?"Expandir menu":"Recolher menu"}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div className="brand"><img className="brandmark has-logo" src="/has-analytics-logo.png" alt="HAS Analytics"/><div><strong>HAS Analytics</strong><small>Inteligência financeira</small></div><button className="close-mobile" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={section===n?"nav active":"nav"} onClick={()=>{if(n==="Acessos"){location.href="/admin/requests";return}setSection(n);setMobile(false)}}><I/><span>{n}</span></button>)}</nav><div className="side-bottom"><button className="nav"><Settings/><span>Preferências</span></button><div className="profile"><div>HA</div><span><b>Haward</b><small>Conta pessoal</small></span><ChevronDown/></div></div></aside>{mobile&&<button className="backdrop" onClick={()=>setMobile(false)} aria-label="Fechar menu"/>}
<main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><p>MINHA VIDA FINANCEIRA · {saveState==="salvando"?"SALVANDO…":saveState==="erro"?"ERRO AO SALVAR":"SALVO"}</p><h1>{section}</h1></div><div className="header-actions"><button className="month" onClick={()=>setMonth(month==="Setembro 2026"?"Outubro 2026":"Setembro 2026")}><CalendarDays/>{month}<ChevronDown/></button><button className="iconbtn" title={userEmail}><Bell/></button><button className="primary" onClick={()=>setImportOpen(true)}><Upload/>Importar extrato</button><button className="add" onClick={()=>setAddOpen(true)}><Plus/></button><button className="iconbtn" onClick={onLogout} title="Sair"><LogOut/></button></div></header>
{section==="Cartões"?<BankCatalog/>:section==="Planejamento"?<Planning/>:section==="Lançamentos"?<TransactionsWorkspace/>:section!=="Visão geral"?<div className="section-placeholder"><div className="placeholder-icon"><Sparkles/></div><h2>{section}</h2><p>Esta área faz parte do seu controle financeiro. Registre lançamentos e volte à visão geral para acompanhar o impacto no mês.</p><button className="primary" onClick={()=>setAddOpen(true)}><Plus/>Novo lançamento</button></div>:<div className="content">
<section className="forecast"><div><span className="eyebrow">SALDO PROJETADO EM 30/09</span><h2>R$ 8.670,28</h2><p><span className="up"><ArrowUpRight/> R$ 318,14</span> acima do saldo inicial</p></div><div className="forecast-right"><div><span>Saldo disponível hoje</span><b>R$ 9.863,02</b></div><div className="line"/><div><span>A receber</span><b className="green">+ {fmt(income)}</b></div><div><span>A pagar</span><b className="red">− R$ 1.538,69</b></div></div></section>
<div className="alert"><Sparkles/><div><b>Seu mês já está 84% planejado</b><span>Depois dos compromissos previstos, restam <strong>R$ 1.192,74</strong> livres para decidir.</span></div><button onClick={()=>setSection("Planejamento")}>Revisar plano</button></div>
<section className="kpis"><Kpi title="Receitas" value={fmt(income)} sub="Previsto no mês" foot="92% já recebido" kind="green"/><Kpi title="Despesas" value={fmt(spent)} sub="de R$ 8.980,34 planejados" foot="77% do orçamento" kind="coral"/><Kpi title="Cartões" value="R$ 5.563,50" sub="faturas de setembro" foot="53% da renda comprometida" kind="cards"/><Kpi title="Reservas" value="R$ 14.886,89" sub="guardados em 3 objetivos" foot="+ R$ 946,44 neste mês" kind="gold"/></section>
<div className="grid-main"><section className="panel cash"><PanelHead title="Fluxo do mês" sub="Realizado e previsto até o fim de setembro" onDetails={()=>setSection("Lançamentos")}/><div className="legend"><span><i className="lg-in"/>Entradas</span><span><i className="lg-out"/>Saídas</span><span><i className="lg-proj"/>Saldo projetado</span></div><div className="chart"><div className="axis"><span>12 mil</span><span>8 mil</span><span>4 mil</span><span>0</span></div><div className="plot">{[35,62,43,72,55,82].map((h,i)=><div className="bars" key={i}><i className="in" style={{height:`${h}%`}}/><i className="out" style={{height:`${Math.max(18,h-22)}%`}}/><span>{["01","06","12","18","24","30"][i]}</span></div>)}<svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M10 155 C100 145 115 120 205 125 S330 75 405 84 S510 48 590 25"/></svg></div></div></section>
<section className="panel categories"><PanelHead title="Para onde foi o dinheiro" sub="Maiores categorias no mês"/><div className="donut-wrap"><div className="donut"><div><b>{fmt(spent)}</b><span>total gasto</span></div></div><div className="cat-list">{cats.slice(0,5).map(([c,v],i)=><div key={c}><span><i className={`c${i}`}/>{initial.find(t=>t.category===c)?.icon||"✨"} {c}</span><b>{fmt(v)}</b></div>)}</div></div></section></div>
<section className="panel transactions"><div className="panel-head"><div><h3>Despesas do mês</h3><p>Despesas confirmadas, previstas e aguardando revisão</p></div><div className="table-actions"><label><Search/><input placeholder="Buscar" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>setAddOpen(true)}><Plus/>Adicionar</button></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Conta / cartão</th><th>Status</th><th>Valor</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td>{t.date}</td><td><span className="tx-icon">{t.icon}</span><b>{t.description}</b>{t.installment&&<small>Parcela {t.installment}</small>}</td><td>{t.category}</td><td>{t.account}</td><td><span className={`status ${t.status}`}>{t.status==="confirmado"?"Confirmado":t.status==="previsto"?"Previsto":"Revisar"}</span></td><td className={t.value>0?"green":""}>{t.value>0?"+ ":"− "}{fmt(t.value)}</td></tr>)}</tbody></table></div></section></div>}</main>
{importOpen&&<div className="modal-bg"><div className="modal"><ModalHead title="Importar extrato" sub="Cole as movimentações copiadas do seu banco." close={()=>{setImportOpen(false);setNotice("")}} icon={<Upload/>}/><div className="steps"><span className="on">1</span><i/><span>2</span><i/><span>3</span><small>Colar extrato</small><small>Conferir</small><small>Importar</small></div><label className="paste-label">EXTRATO BANCÁRIO<textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={"03/09 Supermercado Condor -387,42\n05/09 Salário +5.498,70\n08/09 Mercado Livre -246,80"}/></label><div className="import-note"><Sparkles/><span><b>Leitura inteligente</b> — datas, valores e categorias são reconhecidos; duplicidades são ignoradas.</span></div>{notice&&<p className="notice">{notice}</p>}<div className="modal-foot"><button onClick={()=>setImportOpen(false)}>Cancelar</button><button className="primary" onClick={doImport}>Analisar lançamentos <ArrowUpRight/></button></div></div></div>}
{addOpen&&<div className="modal-bg"><form className="modal small" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setTxs(p=>[{id:Date.now(),date:String(fd.get("date")||"Hoje"),description:String(fd.get("desc")),category:String(fd.get("cat")),icon:"✨",account:"Conta principal",value:-Math.abs(Number(fd.get("value"))||0),status:"confirmado"},...p]);setAddOpen(false)}}><ModalHead title="Novo lançamento" sub="Registre uma despesa ou previsão." close={()=>setAddOpen(false)} icon={<Plus/>}/><div className="form-grid"><label>Data<input name="date" placeholder="04 set" required/></label><label>Valor<input name="value" type="number" step="0.01" placeholder="0,00" required/></label><label className="wide">Descrição<input name="desc" placeholder="Ex.: Mercado" required/></label><label className="wide">Categoria<select name="cat"><option>Mercado</option><option>Moradia</option><option>Transporte</option><option>Compras</option><option>Assinaturas</option><option>Outros</option></select></label></div><div className="modal-foot"><button type="button" onClick={()=>setAddOpen(false)}>Cancelar</button><button className="primary" type="submit"><Check/>Salvar lançamento</button></div></form></div>}</div>}
function Kpi({title,value,sub,foot,kind}:{title:string,value:string,sub:string,foot:string,kind:string}){return <article><div className="kpi-title"><span>{title}</span>{title==="Receitas"?<ArrowDownLeft/>:title==="Despesas"?<ArrowUpRight/>:title==="Cartões"?<WalletCards/>:<PiggyBank/>}</div><h3>{value}</h3><small>{sub}</small>{kind==="cards"?<div className="card-dots"><i/><i/><i/></div>:<div className={`bar ${kind}`}><i style={{width:kind==="gold"?"64%":kind==="coral"?"77%":"92%"}}/></div>}<p><b>{foot}</b></p></article>}
function PanelHead({title,sub,onDetails}:{title:string,sub:string,onDetails?:()=>void}){return <div className="panel-head"><div><h3>{title}</h3><p>{sub}</p></div><button onClick={onDetails}>Ver detalhes</button></div>}
function ModalHead({title,sub,close,icon}:{title:string,sub:string,close:()=>void,icon:React.ReactNode}){return <div className="modal-head"><div><span className="modal-icon">{icon}</span><div><h2>{title}</h2><p>{sub}</p></div></div><button onClick={close} type="button"><X/></button></div>}
type Ledger={id:number;type:"Receita"|"Despesa";name:string;category:string;icon:string;date:string;value:number;account:string;frequency:"Único"|"Mensal"|"Parcelado";installment?:string;remaining?:number;status:"Confirmado"|"Previsto"};
const ledgerSeed:Ledger[]=[
 {id:1,type:"Receita",name:"Salário — Escola",category:"Salários",icon:"💼",date:"05 out",value:5498.70,account:"Conta principal",frequency:"Mensal",status:"Previsto"},
 {id:2,type:"Receita",name:"Bolsa de doutorado",category:"Bolsas",icon:"🎓",date:"08 out",value:3200,account:"Conta principal",frequency:"Mensal",status:"Previsto"},
 {id:3,type:"Receita",name:"Consultoria estatística",category:"Renda extra",icon:"📊",date:"18 out",value:950,account:"Conta principal",frequency:"Único",status:"Previsto"},
 {id:4,type:"Despesa",name:"Aluguel",category:"Moradia",icon:"🏠",date:"10 out",value:1450,account:"Conta principal",frequency:"Mensal",status:"Previsto"},
 {id:5,type:"Despesa",name:"Mercado Livre",category:"Compras",icon:"🛍️",date:"08 out",value:246.80,account:"Inter • 0917",frequency:"Parcelado",installment:"4/6",remaining:2,status:"Confirmado"},
 {id:6,type:"Despesa",name:"Móveis planejados",category:"Casa",icon:"🛋️",date:"18 out",value:490,account:"Nubank • 4421",frequency:"Parcelado",installment:"6/10",remaining:4,status:"Previsto"},
 {id:7,type:"Despesa",name:"Supermercado Condor",category:"Mercado",icon:"🛒",date:"03 out",value:387.42,account:"Nubank • 4421",frequency:"Único",status:"Confirmado"},
 {id:8,type:"Despesa",name:"Spotify",category:"Assinaturas",icon:"🎵",date:"12 out",value:21.90,account:"Nubank • 4421",frequency:"Mensal",status:"Previsto"}
];
const categorySeed=[["Salários","💼","Receita"],["Bolsas","🎓","Receita"],["Renda extra","📊","Receita"],["Moradia","🏠","Despesa"],["Mercado","🛒","Despesa"],["Compras","🛍️","Despesa"],["Casa","🛋️","Despesa"],["Assinaturas","🎵","Despesa"],["Transporte","🚗","Despesa"]];
function TransactionsWorkspace(){
 const [entries,setEntries]=usePersistedFinance<Ledger[]>("ledger",ledgerSeed),[view,setView]=useState<"Todos"|"Receitas"|"Despesas">("Todos"),[search,setSearch]=useState(""),[form,setForm]=useState(false),[categories,setCategories]=usePersistedFinance<string[][]>("categories",categorySeed),[catOpen,setCatOpen]=useState(false),[newCat,setNewCat]=useState("");
 const shown=entries.filter(e=>(view==="Todos"||e.type===view.slice(0,-1))&&(e.name+e.category+e.account).toLowerCase().includes(search.toLowerCase()));
 const revenues=entries.filter(e=>e.type==="Receita").reduce((a,e)=>a+e.value,0),expenses=entries.filter(e=>e.type==="Despesa").reduce((a,e)=>a+e.value,0),monthlyIncome=entries.filter(e=>e.type==="Receita"&&e.frequency==="Mensal").reduce((a,e)=>a+e.value,0),futureInstallments=entries.filter(e=>e.frequency==="Parcelado").reduce((a,e)=>a+e.value*(e.remaining||0),0);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),type=String(fd.get("type")) as "Receita"|"Despesa",frequency=String(fd.get("frequency")) as Ledger["frequency"],total=Math.max(1,Number(fd.get("parts"))||1);setEntries(list=>[{id:Date.now(),type,name:String(fd.get("name")),category:String(fd.get("category")),icon:type==="Receita"?"💰":"✨",date:String(fd.get("date")||"Hoje"),value:Math.abs(Number(fd.get("value"))),account:String(fd.get("account")),frequency,installment:frequency==="Parcelado"?`1/${total}`:undefined,remaining:frequency==="Parcelado"?total-1:undefined,status:"Previsto"},...list]);setForm(false)}
 return <div className="ledger-page">
  <section className="ledger-heading"><div><span>OUTUBRO DE 2026</span><h2>Receitas e despesas</h2><p>Cadastre uma vez e projete automaticamente salários, contas recorrentes e parcelas.</p></div><div><button className="category-btn" onClick={()=>setCatOpen(v=>!v)}><Settings/>Categorias</button><button className="primary ledger-add" onClick={()=>setForm(true)}><Plus/>Novo lançamento</button></div></section>
  <section className="ledger-summary"><article><span>Receitas do mês</span><b className="ledger-green">+ {fmt(revenues)}</b><small>{fmt(monthlyIncome)} se repetem mensalmente</small></article><article><span>Despesas do mês</span><b className="ledger-red">− {fmt(expenses)}</b><small>{entries.filter(e=>e.type==="Despesa"&&e.frequency==="Mensal").length} compromissos recorrentes</small></article><article><span>Saldo previsto</span><b>{fmt(revenues-expenses)}</b><small>Considerando todos os lançamentos</small></article><article><span>Parcelas futuras</span><b>{fmt(futureInstallments)}</b><small>A receber nas próximas faturas</small></article></section>
  {catOpen&&<section className="category-manager"><div><h3>Categorias personalizadas</h3><p>Organize receitas e despesas do seu jeito.</p></div><div className="category-chips">{categories.map((c,i)=><span key={c[0]}>{c[1]} {c[0]}<small>{c[2]}</small><button onClick={()=>setCategories(list=>list.filter((_,j)=>j!==i))}>×</button></span>)}</div><form onSubmit={e=>{e.preventDefault();if(newCat.trim()){setCategories(list=>[...list,[newCat,"✨","Despesa"]]);setNewCat("")}}}><input value={newCat} onChange={e=>setNewCat(e.target.value)} placeholder="Nome da nova categoria"/><button><Plus/>Criar categoria</button></form></section>}
  <section className="panel ledger-panel"><div className="ledger-toolbar"><div className="ledger-tabs">{(["Todos","Receitas","Despesas"] as const).map(t=><button className={view===t?"active":""} onClick={()=>setView(t)} key={t}>{t}<span>{t==="Todos"?entries.length:t==="Receitas"?entries.filter(e=>e.type==="Receita").length:entries.filter(e=>e.type==="Despesa").length}</span></button>)}</div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamento, categoria ou conta"/></label></div>
   <div className="ledger-list"><div className="ledger-row ledger-labels"><span>Data</span><span>Lançamento</span><span>Categoria</span><span>Conta ou cartão</span><span>Repetição</span><span>Valor</span></div>{shown.map(e=><article className="ledger-row" key={e.id}><span>{e.date}</span><div><i>{e.icon}</i><p><b>{e.name}</b><small>{e.status}</small></p></div><span className="ledger-category">{e.category}</span><span>{e.account}</span><div><b className="frequency">{e.frequency}</b>{e.installment&&<small>Parcela {e.installment} · faltam {e.remaining}</small>}</div><strong className={e.type==="Receita"?"ledger-green":"ledger-red"}>{e.type==="Receita"?"+":"−"} {fmt(e.value)}</strong></article>)}</div>
  </section>
  <section className="recurrence-strip"><div><Sparkles/><span><b>Projeção automática</b><small>Os lançamentos mensais serão repetidos; os parcelados avançarão a parcela até o encerramento.</small></span></div><div><span>NOVEMBRO</span><b>{fmt(monthlyIncome-entries.filter(e=>e.type==="Despesa"&&e.frequency==="Mensal").reduce((a,e)=>a+e.value,0)-entries.filter(e=>e.frequency==="Parcelado").reduce((a,e)=>a+e.value,0))}</b></div><div><span>DEZEMBRO</span><b>{fmt(monthlyIncome-entries.filter(e=>e.type==="Despesa"&&e.frequency==="Mensal").reduce((a,e)=>a+e.value,0)-entries.filter(e=>e.frequency==="Parcelado").reduce((a,e)=>a+e.value,0))}</b></div></section>
  {form&&<div className="modal-bg"><form className="modal ledger-modal" onSubmit={submit}><ModalHead title="Novo lançamento" sub="Defina se o valor acontece uma vez, todo mês ou em parcelas." close={()=>setForm(false)} icon={<Plus/>}/><div className="ledger-form"><label>Tipo<select name="type"><option>Despesa</option><option>Receita</option></select></label><label>Descrição<input name="name" required placeholder="Ex.: Salário, aluguel ou compra"/></label><label>Valor da parcela ou lançamento<input name="value" type="number" step=".01" required placeholder="0,00"/></label><label>Data<input name="date" required placeholder="15 out"/></label><label>Categoria<select name="category">{categories.map(c=><option key={c[0]}>{c[0]}</option>)}</select></label><label>Conta ou cartão<select name="account"><option>Conta principal</option><option>Nubank • 4421</option><option>Inter • 0917</option><option>Dinheiro</option></select></label><label>Repetição<select name="frequency"><option>Único</option><option>Mensal</option><option>Parcelado</option></select></label><label>Número de parcelas<input name="parts" type="number" min="1" placeholder="Preencha se parcelado"/></label></div><div className="modal-foot"><button type="button" onClick={()=>setForm(false)}>Cancelar</button><button className="primary"><Check/>Salvar e projetar</button></div></form></div>}
 </div>
}
type PlanItem={id:number;name:string;category:string;icon:string;date:string;value:number;kind:"Fixo"|"Fatura"|"Parcela";detail?:string;active:boolean};
const initialPlan:PlanItem[]=[
{id:1,name:"Aluguel",category:"Moradia",icon:"🏠",date:"10 out",value:1450,kind:"Fixo",active:true},
{id:2,name:"Energia elétrica",category:"Casa",icon:"💡",date:"12 out",value:220,kind:"Fixo",active:true},
{id:3,name:"Internet",category:"Casa",icon:"🌐",date:"15 out",value:119.90,kind:"Fixo",active:true},
{id:4,name:"Fatura Nubank",category:"Cartões",icon:"💳",date:"25 out",value:2780.40,kind:"Fatura",active:true},
{id:5,name:"Fatura Inter",category:"Cartões",icon:"💳",date:"20 out",value:1635.80,kind:"Fatura",active:true},
{id:6,name:"Mercado Livre",category:"Compras",icon:"🛍️",date:"08 out",value:246.80,kind:"Parcela",detail:"4 de 6",active:true},
{id:7,name:"Móveis",category:"Casa",icon:"🛋️",date:"18 out",value:490,kind:"Parcela",detail:"6 de 10",active:true},
{id:8,name:"Academia",category:"Saúde",icon:"🏋️",date:"06 out",value:89.90,kind:"Fixo",active:true}
];
const initialBudgets=[{name:"Mercado",icon:"🛒",value:1100,color:"cyan"},{name:"Transporte",icon:"🚗",value:650,color:"blue"},{name:"Lazer e fim de semana",icon:"🎬",value:500,color:"violet"},{name:"Delivery",icon:"🛵",value:250,color:"coral"}];
function Planning(){
 const [income,setIncome]=usePersistedFinance<number>("planning-income",10491.22),[reserve,setReserve]=usePersistedFinance<number>("planning-reserve",1200),[items,setItems]=usePersistedFinance<PlanItem[]>("planning-items",initialPlan),[budgets,setBudgets]=usePersistedFinance<typeof initialBudgets>("planning-budgets",initialBudgets),[editing,setEditing]=useState(false);
 const commitments=items.filter(i=>i.active).reduce((sum,i)=>sum+i.value,0),flexible=budgets.reduce((sum,i)=>sum+i.value,0),free=income-commitments-flexible-reserve,plannedPct=Math.min(100,Math.round(((commitments+flexible+reserve)/income)*100));
 const changeBudget=(index:number,value:number)=>setBudgets(list=>list.map((b,i)=>i===index?{...b,value:Math.max(0,value)}:b));
 return <div className="planning-page">
  <section className="planning-top"><div><span className="planning-kicker"><CalendarDays/> PLANO DE OUTUBRO</span><h2>Decida o mês antes que ele comece.</h2><p>Organize compromissos, limites de gasto e reservas. O saldo livre é recalculado a cada ajuste.</p></div><div className="planning-score"><span>PLANEJADO</span><b>{plannedPct}%</b><div><i style={{width:`${plannedPct}%`}}/></div><small>{free>=0?"Seu plano está dentro da renda prevista.":"Seu plano ultrapassou a renda prevista."}</small></div></section>
  <section className="plan-summary">
   <article><span><TrendingUp/>Receita prevista</span><label>R$ <input aria-label="Receita prevista" type="number" step="100" value={income} onChange={e=>setIncome(Number(e.target.value))}/></label><small>Salários e outras entradas</small></article>
   <article><span><ReceiptText/>Compromissos</span><b>{fmt(commitments)}</b><small>{items.filter(i=>i.active).length} despesas programadas</small></article>
   <article><span><Target/>Reserva planejada</span><label>R$ <input aria-label="Reserva planejada" type="number" step="50" value={reserve} onChange={e=>setReserve(Number(e.target.value))}/></label><small>Valor separado antes de gastar</small></article>
   <article className={free<0?"free-card danger":"free-card"}><span><Wallet/>Saldo livre projetado</span><b>{free<0?"− ":""}{fmt(free)}</b><small>Depois de todo o plano</small></article>
  </section>
  <div className="planning-grid">
   <section className="panel plan-commitments"><div className="panel-head"><div><h3>Compromissos do mês</h3><p>Ative apenas o que realmente entrará em outubro</p></div><button onClick={()=>setEditing(v=>!v)}>{editing?"Concluir":"Editar plano"}</button></div><div className="commitment-list">{items.map(item=><article className={item.active?"":"disabled"} key={item.id}><button className="plan-check" onClick={()=>setItems(list=>list.map(i=>i.id===item.id?{...i,active:!i.active}:i))} aria-label={item.active?"Retirar do plano":"Incluir no plano"}>{item.active?<CircleCheck/>:<Circle/>}</button><span className="plan-emoji">{item.icon}</span><div><b>{item.name}</b><small>{item.date} · {item.kind}{item.detail?` · ${item.detail}`:""}</small></div>{editing?<label className="plan-value">R$ <input type="number" value={item.value} onChange={e=>setItems(list=>list.map(i=>i.id===item.id?{...i,value:Number(e.target.value)}:i))}/></label>:<strong>{fmt(item.value)}</strong>}{editing&&<button className="plan-remove" onClick={()=>setItems(list=>list.filter(i=>i.id!==item.id))}><Trash2/></button>}</article>)}</div><button className="add-commitment" onClick={()=>setItems(list=>[...list,{id:Date.now(),name:"Novo compromisso",category:"Outros",icon:"✨",date:"30 out",value:0,kind:"Fixo",active:true}])}><Plus/>Adicionar compromisso</button></section>
   <section className="panel plan-budgets"><div className="panel-head"><div><h3>Limites para gastos variáveis</h3><p>Defina quanto pode gastar sem comprometer o plano</p></div></div><div className="budget-list">{budgets.map((budget,index)=><article key={budget.name}><div className={`budget-icon ${budget.color}`}>{budget.icon}</div><div><b>{budget.name}</b><span>Limite mensal</span></div><label>R$ <input type="number" step="50" value={budget.value} onChange={e=>changeBudget(index,Number(e.target.value))}/></label></article>)}</div><div className="budget-total"><span>Total reservado para variáveis</span><b>{fmt(flexible)}</b></div><div className="planning-tip"><Sparkles/><p><b>Margem inteligente</b><br/>Mantenha ao menos 10% da renda livre para imprevistos. Sua margem atual é <strong>{Math.round((free/income)*100)}%</strong>.</p></div></section>
  </div>
  <section className="panel horizon"><div className="panel-head"><div><h3>Visão dos próximos 90 dias</h3><p>Parcelas e compromissos que continuarão nos meses seguintes</p></div></div><div className="horizon-grid"><article><span>OUT</span><b>{fmt(commitments+flexible)}</b><small>Plano atual</small></article><i/><article><span>NOV</span><b>R$ 6.497,80</b><small>7 compromissos previstos</small></article><i/><article><span>DEZ</span><b>R$ 5.941,00</b><small>5 compromissos previstos</small></article></div></section>
 </div>
}
type FinanceCard={id:number;bank:string;logo:string;last4:string;closing:number;due:number;color:string;color2:string};
const bankCatalog=[
 ["Nubank","#820ad1","#4c0677","NU"],["Inter","#ff7a00","#c94d00","inter"],["Itaú","#ec7000","#073f87","itaú"],["Banco do Brasil","#f9dc16","#173863","BB"],["Caixa","#087bb8","#005ca9","CAIXA"],["Bradesco","#cc092f","#8e0623","bradesco"],["Santander","#ec0000","#9e0000","S"],["C6 Bank","#242424","#050505","C6"],["BTG Pactual","#18365f","#071a34","BTG"],["XP","#171717","#000000","XP"],["Sicredi","#68a82f","#39751e","sicredi"],["Sicoob","#006b5b","#003b37","sicoob"],["PicPay","#21c25e","#087f42","PicPay"],["Mercado Pago","#16aee8","#0876b9","mercado pago"],["PagBank","#42b549","#187c31","PagBank"],["Neon","#00b8e6","#006ed0","neon"]
] as const;
const initialCards:FinanceCard[]=[
 {id:1,bank:"Nubank",logo:"NU",last4:"4421",closing:18,due:25,color:"#820ad1",color2:"#4c0677"},
 {id:2,bank:"Inter",logo:"inter",last4:"0917",closing:12,due:20,color:"#ff7a00",color2:"#c94d00"}
];
function BankCatalog(){
 const [cards,setCards]=usePersistedFinance<FinanceCard[]>("cards",initialCards),[q,setQ]=useState(""),[editing,setEditing]=useState<FinanceCard|null>(null);
 const banks=bankCatalog.filter(b=>b[0].toLowerCase().includes(q.toLowerCase()));
 function openCard(bank?:typeof bankCatalog[number]){setEditing({id:Date.now(),bank:bank?.[0]||"",color:bank?.[1]||"#063b70",color2:bank?.[2]||"#021b3a",logo:bank?.[3]||"CARD",last4:"",closing:1,due:10})}
 function saveCard(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const next:FinanceCard={id:editing!.id,bank:String(fd.get("bank")).trim(),logo:String(fd.get("logo")).trim()||"CARD",last4:String(fd.get("last4")).replace(/\D/g,"").slice(-4).padStart(4,"0"),closing:Number(fd.get("closing")),due:Number(fd.get("due")),color:String(fd.get("color")),color2:String(fd.get("color2"))};setCards(list=>list.some(c=>c.id===next.id)?list.map(c=>c.id===next.id?next:c):[...list,next]);setEditing(null)}
 return <div className="bank-page"><div className="bank-title"><div><span className="bank-kicker">CARTEIRA DE CARTÕES</span><h2>Meus cartões e bancos</h2><p>Cadastre seus cartões com as cores reais e mantenha fechamento e vencimento sempre atualizados.</p></div><div className="bank-title-actions"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar instituição"/></label><button className="primary" onClick={()=>openCard()}><Plus/>Adicionar cartão</button></div></div>
 <div className="selected-banks"><div className="selected-heading"><h3>Seus cartões</h3><small>{cards.length} {cards.length===1?"cartão cadastrado":"cartões cadastrados"}</small></div>{cards.length?<div>{cards.map(card=><article className="credit-visual" key={card.id} style={{background:`linear-gradient(135deg,${card.color},${card.color2})`}}><div className="card-shine"/><div className="card-top"><span>{card.logo}</span><CreditCard/></div><b>••••&nbsp; {card.last4}</b><small>Fechamento dia {card.closing} · Vencimento dia {card.due}</small><button className="edit-card" onClick={()=>setEditing(card)} aria-label={`Editar cartão ${card.bank}`}><Pencil/>Editar</button><strong>{card.bank}</strong></article>)}</div>:<div className="empty-cards"><CreditCard/><b>Nenhum cartão cadastrado</b><span>Adicione seu primeiro cartão para acompanhar as próximas faturas.</span><button className="primary" onClick={()=>openCard()}><Plus/>Adicionar cartão</button></div>}</div>
 <h3>Catálogo de instituições</h3><div className="bank-grid">{banks.map(bank=>{const added=cards.some(c=>c.bank===bank[0]);return <button key={bank[0]} className={added?"bank-option chosen":"bank-option"} onClick={()=>added?setEditing(cards.find(c=>c.bank===bank[0])!):openCard(bank)}><span className="bank-logo" style={{background:`linear-gradient(135deg,${bank[1]},${bank[2]})`,color:bank[0]==="Banco do Brasil"?"#173863":"white"}}>{bank[3]}</span><b>{bank[0]}</b><small>{added?"Editar cartão":"Adicionar cartão"}</small>{added&&<Check/>}</button>})}<button className="bank-option custom-bank" onClick={()=>openCard()}><span className="bank-logo"><Plus/></span><b>Outra instituição</b><small>Cadastrar manualmente</small></button></div>
 {editing&&<div className="modal-bg"><form className="modal card-modal" onSubmit={saveCard}><ModalHead title={cards.some(c=>c.id===editing.id)?"Editar cartão":"Adicionar cartão"} sub="Escolha a identidade visual e atualize as datas da fatura." close={()=>setEditing(null)} icon={<CreditCard/>}/><div className="card-preview" style={{background:`linear-gradient(135deg,${editing.color},${editing.color2})`}}><span>{editing.logo||"CARD"}</span><b>••••&nbsp; {editing.last4||"0000"}</b><small>Fechamento dia {editing.closing} · Vencimento dia {editing.due}</small></div><fieldset className="card-palettes"><legend>Cores do cartão</legend><div>{bankCatalog.slice(0,8).map(bank=><button type="button" key={bank[0]} className={editing.color===bank[1]&&editing.color2===bank[2]?"active":""} onClick={()=>setEditing({...editing,bank:editing.bank||bank[0],logo:editing.logo==="CARD"?bank[3]:editing.logo,color:bank[1],color2:bank[2]})}><i style={{background:`linear-gradient(135deg,${bank[1]},${bank[2]})`}}/><span>{bank[0]}</span>{editing.color===bank[1]&&editing.color2===bank[2]&&<Check/>}</button>)}</div></fieldset><div className="card-form"><label>Instituição<input name="bank" required value={editing.bank} onChange={e=>{const match=bankCatalog.find(b=>b[0].toLowerCase()===e.target.value.toLowerCase());setEditing({...editing,bank:e.target.value,...(match?{logo:match[3],color:match[1],color2:match[2]}:{})})}} placeholder="Ex.: Nubank"/></label><label>Nome curto / logo<input name="logo" value={editing.logo} onChange={e=>setEditing({...editing,logo:e.target.value})} maxLength={12} placeholder="Ex.: NU"/></label><label>Final do cartão<input name="last4" inputMode="numeric" required value={editing.last4} onChange={e=>setEditing({...editing,last4:e.target.value.replace(/\D/g,"").slice(0,4)})} maxLength={4} placeholder="0000"/></label><label>Fechamento<input name="closing" type="number" min="1" max="31" required value={editing.closing} onChange={e=>setEditing({...editing,closing:Number(e.target.value)})}/></label><label>Vencimento<input name="due" type="number" min="1" max="31" required value={editing.due} onChange={e=>setEditing({...editing,due:Number(e.target.value)})}/></label><label className="color-field">Cor principal<input name="color" type="color" value={editing.color} onChange={e=>setEditing({...editing,color:e.target.value})}/></label><label className="color-field">Cor de apoio<input name="color2" type="color" value={editing.color2} onChange={e=>setEditing({...editing,color2:e.target.value})}/></label></div><div className="modal-foot card-modal-foot">{cards.some(c=>c.id===editing.id)&&<button className="delete-card" type="button" onClick={()=>{setCards(list=>list.filter(c=>c.id!==editing.id));setEditing(null)}}><Trash2/>Excluir</button>}<span/><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" type="submit"><Check/>Salvar cartão</button></div></form></div>}</div>
}
