"use client";
import {useEffect,useState} from "react";
import {Check,ChevronLeft,Copy,KeyRound,Mail,X} from "lucide-react";
import {supabase} from "../../../lib/supabase";
type Row={id:number;name:string;email:string;status:string;created_at:string;approved_at:string|null};
export default function AdminRequests(){
 const [rows,setRows]=useState<Row[]>([]),[key,setKey]=useState<{email:string,key:string}|null>(null),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState("");
 async function api(method:"GET"|"POST",body?:unknown){const {data}=await supabase.auth.getSession();return fetch("/api/admin/access",{method,headers:{"content-type":"application/json",authorization:`Bearer ${data.session?.access_token||""}`},body:body?JSON.stringify(body):undefined})}
 useEffect(()=>{api("GET").then(async r=>{const j=await r.json();if(r.ok)setRows(j.rows);else setError(j.error||"Acesso restrito ao administrador.")})},[]);
 async function action(id:number,type:"approve"|"reject"){setBusy(id);const r=await api("POST",{id,type}),j=await r.json();setBusy(null);if(r.ok){setRows(p=>p.map(x=>x.id===id?{...x,status:type==="approve"?"approved":"rejected"}:x));if(j.key)setKey({email:j.email,key:j.key})}else setError(j.error)}
 return <main className="admin-page"><header className="admin-head"><div><a href="/"><ChevronLeft/></a><span><KeyRound/></span><div><small>ADMINISTRAÇÃO</small><h1>Solicitações de acesso</h1></div></div><b>{rows.filter(r=>r.status==="pending").length} pendentes</b></header>{error&&<div className="access-message">{error}</div>}{key&&<section className="key-result"><div><Check/><span><b>Chave criada para {key.email}</b><code>{key.key}</code></span></div><button onClick={()=>navigator.clipboard.writeText(key.key)}><Copy/>Copiar chave</button></section>}<section className="requests-list">{!error&&rows.length===0?<div className="empty-requests"><Mail/><h2>Nenhuma solicitação</h2><p>Os novos pedidos aparecerão aqui.</p></div>:rows.map(r=><article key={r.id}><div className="request-avatar">{r.name.slice(0,2).toUpperCase()}</div><div className="request-info"><h3>{r.name}</h3><p>{r.email}</p><small>{new Date(r.created_at).toLocaleDateString("pt-BR")}</small></div><span className={`request-status ${r.status}`}>{r.status==="pending"?"Pendente":r.status==="approved"?"Aprovado":"Recusado"}</span>{r.status==="pending"&&<div className="request-actions"><button disabled={busy===r.id} onClick={()=>action(r.id,"reject")}><X/>Recusar</button><button className="approve" disabled={busy===r.id} onClick={()=>action(r.id,"approve")}><Check/>Aprovar e gerar chave</button></div>}</article>)}</section></main>
}
